services:
  db:
    build:
      context: ./deploy/db
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3306:3306'
    networks:
      - default
    volumes:
      - db_data:/var/lib/mysql
      - ./deploy/db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # Check for the testing database to be ready, meaning the entrypoint script finished running
      test: mysql testing -uroot -proot --silent --execute "select 1;"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret

  app:
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    networks:
      - default
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./migrations/:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    environment:
      # App settings
      HOST: 0.0.0.0
      PORT: 3000
      # Database settings
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_USERNAME: app
      MYSQL_DATABASE_PASSWORD: secret
      MYSQL_DATABASE_NAME: app

networks:
  default:

volumes:
  db_data:
  app_data:
