apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastfood.fullname" . }}-db-config
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
data:
  db.database: {{ .Values.db.databaseName | quote }}
  db.password: {{ .Values.db.password | quote }}
  db.port: {{ .Values.db.port | quote }}
  db.root_password: {{ .Values.db.rootPassword | quote }}
  db.user: {{ .Values.db.user | quote }}