apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastfood.fullname" . }}-db-secret
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
type: Opaque
stringData:
  db.database: {{ .Values.db.databaseName | quote }}
  db.password: {{ .Values.db.password | quote }}
  db.port: {{ .Values.db.port | quote }}
  db.root_password: {{ .Values.db.rootPassword | quote }}
  db.user: {{ .Values.db.user | quote }}