apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastfood.fullname" . }}-monolith-config
  labels:
  {{- include "fastfood.labels" . | nindent 4 }}
data:
  app.host: {{ .Values.monolith.host | quote }}
  app.port: {{ .Values.monolith.port | quote }}