apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "fastfood.fullname" . }}-cronjob
  labels:
    app.kubernetes.io/component: monolith
  {{- include "fastfood.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: {{ .Values.webhook.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ include "fastfood.fullname" . }}-webhook
            image: {{ .Values.webhook.image }}:{{ .Values.webhook.tag }}
            env:
            - name: WEBHOOK_URL
              value: http://{{ include "fastfood.fullname" . }}-monolith-service.default.svc.cluster.local/{{ .Values.webhook.path }}
            - name: MYSQL_DATABASE_HOST
              value: {{ include "fastfood.fullname" . }}-db-service.default.svc.cluster.local
            - name: MYSQL_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  key: db.port
                  name: {{ include "fastfood.fullname" . }}-db-secret
            - name: MYSQL_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db.user
                  name: {{ include "fastfood.fullname" . }}-db-secret
            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db.password
                  name: {{ include "fastfood.fullname" . }}-db-secret
            - name: MYSQL_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: db.database
                  name: {{ include "fastfood.fullname" . }}-db-secret
          restartPolicy: Never