name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          access_token_lifetime: 300s
          credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCLOUD_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push the app Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: ${{ secrets.GCLOUD_REGISTRY }}/${{ secrets.GCLOUD_PROJECT_ID }}/fastfood-monolith:${{ github.sha }}

      - name: Build and push the db Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/db
          push: true
          tags: ${{ secrets.GCLOUD_REGISTRY }}/${{ secrets.GCLOUD_PROJECT_ID }}/fastfood-db:${{ github.sha }}
